site_name: FrontISTR solver plugin for FreeCAD
theme:
    name: 'readthedocs'
    highlightjs: true
    language: 'ja'

use_directory_urls: false

nav:
- ホーム: index.md
- インストール: install.md
- GUI から FEM_FrontISTRを実行する: usegui.md
- スクリプトによる静解析: usescript.md
